name: Build docker image

on:
  push:
    branches:
      - 'master'
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: ${{ vars.DOCKER_REGISTRY }}/${{ github.repository }}/lolcat
    environment:
      name: GITHUB_REGISTRY
    steps:
    - name: checkout Dockerfile
      uses: actions/checkout@v4

    - name: set metadata for image
      uses: docker/metadata-action@v5
      id: meta
      with:
        images: ${{ env.DOCKER_IMAGE }}

    - name: login to github
      uses: docker/login-action@v3
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: ${{ vars.DOCKER_REGISTRY }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ${{ steps.meta.outputs.tags }}